GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Hi",
    "author": "Me",
    "url": "test.com",
    "likes": 30
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Alo",
    "author": "Melbourne",
    "url": "test.com",
    "likes": 99
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Kiki is a cat",
    "author": "Me Hotel",
    "url": "test.com",
    "likes": 99
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Kiki is a dog",
    "author": "Me Hotel",
    "likes": 99
}
###
DELETE http://localhost:3003/api/blogs/654
###
PUT http://localhost:3003/api/blogs/654439f3a1087ee1c0e0dc51
Content-Type: application/json

{
    "title": "Kiki is a cat",
    "author": "Me Hotel",
    "url": "test.com",
    "likes": 9999
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Kiki",
    "name": "Me Hotel",
    "password": "meowmeow"
}